-- noinspection SqlDialectInspectionForFile
-- noinspection SqlNoDataSourceInspectionForFile

CREATE SCHEMA IF NOT EXISTS cnm;

CREATE TABLE IF NOT EXISTS cnm.inventory(
  id            BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    BIGINT          NOT NULL,
  updated_at    BIGINT          NOT NULL,
  version       BIGINT          NOT NULL,
  product_id    VARCHAR(32)     NOT NULL,
  product_name  VARCHAR(255)    NOT NULL,
  remains       INTEGER         NOT NULL
);